# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: oh-hi, I'm Matt
email: morcutt@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a proven product designer who has delivered engaging digital experiences for in both enterprise and startup environments. My passions revolves around innovating interaction design, coaching/collaborating design strategy, even digging into the code, but mostly its finding beauty through simplicity.
description-cont: >- # this means to ignore newlines until "baseurl:"
  I have experince in product strategy, user research, information architecture, interaction design, front end development, data visualization, and machine learning / AI
description-cont-too: >- # this means to ignore newlines until "baseurl:"
  You fan find more about me at the following sites below.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: morcutt
github_username:  morcutt

# Build settings
markdown: kramdown
theme: jekyll-swiss
plugins:
  - jekyll-feed
permalink: /work/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
